dev/src/src/main/java/com/gconsulting/webapp/action/APIsAction.java
package com.gconsulting.webapp.action;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVParser;
import org.apache.commons.csv.CSVRecord;
import org.primefaces.model.UploadedFile;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.gconsulting.Constants;
import com.gconsulting.model.API;
import com.gconsulting.model.Exchange;
import com.gconsulting.model.FeeApiType;
import com.gconsulting.model.Market;
import com.gconsulting.model.ids.FeeApiId;
import com.gconsulting.model.ids.FeeApiTypeId;
import com.gconsulting.service.ExchangeManager;
import com.gconsulting.webapp.util.ImportUtils;

@SuppressWarnings("unchecked")
@Scope("request")
@Component("apisAction")
public class APIsAction extends BasePage implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7276861502829761813L;
	private ExchangeManager exchangeManager;
	private API selectedAPI = new API();
	private UploadedFile importFile;
	private String exchangeCode;
	private String type;

	@Autowired
	public void setExchangeManager(
			@Qualifier("exchangeManager") ExchangeManager exchangeManager) {
		this.exchangeManager = exchangeManager;
	}

	public APIsAction() {
		setSortColumn("exchange.code"); // sets the default sort column
	}

	public List<API> getAPIs() {
		return sort(exchangeManager.getAllApi());
	}

	public List<String> getExchanges() {

		List<String> exchangesString = new ArrayList<String>();
		List<Exchange> exchanges = exchangeManager.getAllExchange();
		for (Exchange exchange : exchanges) {
			exchangesString.add(exchange.getCode());
		}
		return exchangesString;
	}

	public List<String> getAPITypes() {

		List<String> typesString = new ArrayList<String>();
		List<FeeApiType> types = exchangeManager.getAllType();
		for (FeeApiType type : types) {
			typesString
					.add(type.getMarket().getCode() + " - " + type.getType());
		}
		return typesString;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public API getSelectedAPI() {
		return selectedAPI;
	}

	public void setSelectedAPI(API selectedAPI) {
		this.selectedAPI = selectedAPI;
	}

	public String getExchangeCode() {
		return exchangeCode;
	}

	public void setExchangeCode(String exchangeCode) {
		this.exchangeCode = exchangeCode;
	}

	public UploadedFile getImportFile() {
		return importFile;
	}

	public void setImportFile(UploadedFile importFile) {
		this.importFile = importFile;
	}

	public String importAPIs() {

		HttpServletRequest request = getRequest();
		// write the file to the filesystem
		// the directory to upload to
		String uploadDir = getFacesContext().getExternalContext().getRealPath(
				"/resources");
		// The following seems to happen when running jetty:run
		if (uploadDir == null) {
			uploadDir = new File("src/main/webapp/resources").getAbsolutePath();
		}
		uploadDir += "/" + request.getRemoteUser() + "/";
		try {
			String filename = importFile.getFileName();
			if (filename.endsWith(Constants.CSV_SUFFIX)) {
				// Create the CSVFormat object
				CSVFormat format = CSVFormat.RFC4180.withHeader()
						.withDelimiter(';');
				CSVParser parser = new CSVParser(new FileReader(
						ImportUtils.saveFile(importFile, uploadDir)), format);
				int i = 0, total = 0;
				String skippedSummary = new String();
				for (CSVRecord csvType : parser.getRecords()) {
					String marketCodeTemp = csvType
							.get(Constants.APIS_IMPORT_HEADER2);
					Market market = new Market();
					if (exchangeManager.getMarketByCode(marketCodeTemp) == null) {
						market = new Market(marketCodeTemp, marketCodeTemp
								+ " market");
						exchangeManager.create(market);
					} else {
						market = exchangeManager
								.getMarketByCode(marketCodeTemp);
					}
					String typeTemp = csvType
							.get(Constants.APIS_IMPORT_HEADER3);
					FeeApiType type = new FeeApiType();
					if (exchangeManager.getTypeById(new FeeApiTypeId(typeTemp,
							market)) == null) {
						type = new FeeApiType(typeTemp, market);
						exchangeManager.create(type);
					} else {
						type = exchangeManager.getTypeById(new FeeApiTypeId(
								typeTemp, market));
					}
					API api = new API();
					api.setExchange(exchangeManager.getExchangeByCode(csvType
							.get(Constants.APIS_IMPORT_HEADER1)));
					api.setFeeType(type);
					api.setAddress(csvType.get(Constants.APIS_IMPORT_HEADER4));
					if (exchangeManager.getApiById(new FeeApiId(api
							.getExchange(), api.getFeeType())) == null) {
						exchangeManager.create(api);
						i++;
					} else {
						if ((total - i) < Constants.SKIPPED_SUMMARY_LENGTH) {
							skippedSummary = skippedSummary.concat(api
									.getExchange().getCode()
									+ " "
									+ api.getFeeType().getMarket().getCode()
									+ " "
									+ api.getFeeType().getType()
									+ " "
									+ api.getAddress() + "\\n");
						}
					}
					total++;
				}
				// close the parser
				parser.close();
				addFacesMessage("apis.import.imported");
				addFacesMessage("apis.import.importedSummary", new Object[] { i,
						total - i, skippedSummary });
			} else {
				addFacesError("apis.import.error");
			}
		} catch (IOException e) {
			addFacesError("apis.import.error");
		}
		return "list";
	}

	public String delete() {

		exchangeManager.delete(selectedAPI);
		addFacesMessage("apis.deleted");
		return "list";
	}

	public String edit() {

		String typeType = null;
		String typeMarketCode = null;
		if (exchangeCode == null) {
			exchangeCode = new String(getParameter("exchangeCode"));
		}
		if (typeMarketCode == null) {
			typeMarketCode = new String(getParameter("marketCode"));
		}
		if (typeType == null) {
			typeType = new String(getParameter("type"));
		}
		type = typeMarketCode + " - " + typeType;
		Exchange selectedExchange = exchangeManager
				.getExchangeByCode(exchangeCode);
		Market selectedMarket = exchangeManager.getMarketByCode(typeMarketCode);
		FeeApiType apiType = new FeeApiType(typeType, selectedMarket);
		selectedAPI = exchangeManager.getApiById(new FeeApiId(selectedExchange,
				apiType));
		return "edit";
	}

	public String save() {

		String typeType = null;
		String typeMarketCode = null;
		String key = new String("");
		Exchange selectedExchange = exchangeManager
				.getExchangeByCode(exchangeCode);
		if (type != null) {
			if (type.length() > 0) {
				typeMarketCode = type.substring(0, type.indexOf(" - "));
				typeType = type.substring(type.indexOf(" - ") + 3);
			}
		}
		Market selectedMarket = new Market();
		if (exchangeManager.getMarketByCode(typeMarketCode) == null) {
			selectedMarket = new Market(typeMarketCode, typeMarketCode
					+ " market");
			exchangeManager.create(selectedMarket);
		} else {
			selectedMarket = exchangeManager.getMarketByCode(typeMarketCode);
		}
		FeeApiType apiType = new FeeApiType();
		if (exchangeManager.getTypeById(new FeeApiTypeId(typeType,
				selectedMarket)) == null) {
			apiType = new FeeApiType(typeType, selectedMarket);
			exchangeManager.create(apiType);
		} else {
			apiType = exchangeManager.getTypeById(new FeeApiTypeId(typeType,
					selectedMarket));
		}
		selectedAPI.setExchange(selectedExchange);
		selectedAPI.setFeeType(apiType);
		boolean isUpdate = (exchangeManager.getApiById(new FeeApiId(selectedAPI
				.getExchange(), selectedAPI.getFeeType())) == null) ? false
				: true;
		if (!isUpdate) {
			exchangeManager.create(selectedAPI);
			key = "apis.added";
		} else {
			exchangeManager.update(selectedAPI);
			key = "apis.updated";
		}
		addFacesMessage(key);
		return "list";
	}
}

dev/src/src/main/java/com/gconsulting/webapp/action/ExchangesAction.java
package com.gconsulting.webapp.action;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.Serializable;
import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVParser;
import org.apache.commons.csv.CSVRecord;
import org.primefaces.model.UploadedFile;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.gconsulting.Constants;
import com.gconsulting.model.Exchange;
import com.gconsulting.service.ExchangeManager;
import com.gconsulting.webapp.util.ImportUtils;

@SuppressWarnings("unchecked")
@Scope("request")
@Component("exchangeAction")
public class ExchangesAction extends BasePage implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4820984471948349094L;

	private ExchangeManager exchangeManager;
	private Exchange selectedExchange = new Exchange();
	private UploadedFile importFile;
	private String code;

	@Autowired
	public void setExchangeManager(
			@Qualifier("exchangeManager") ExchangeManager exchangeManager) {
		this.exchangeManager = exchangeManager;
	}

	public ExchangesAction() {
		setSortColumn("code"); // sets the default sort column
		// isUpdate = false;
	}

	public List<Exchange> getExchanges() {
		return sort(exchangeManager.getAllExchange());
	}

	public Exchange getSelectedExchange() {
		return selectedExchange;
	}

	public void setSelectedExchange(Exchange selectedExchange) {
		this.selectedExchange = selectedExchange;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public UploadedFile getImportFile() {
		return importFile;
	}

	public void setImportFile(UploadedFile importFile) {
		this.importFile = importFile;
	}

	public String importExchanges() {

		HttpServletRequest request = getRequest();
		// write the file to the filesystem
		// the directory to upload to
		String uploadDir = getFacesContext().getExternalContext().getRealPath(
				"/resources");
		// The following seems to happen when running jetty:run
		if (uploadDir == null) {
			uploadDir = new File("src/main/webapp/resources").getAbsolutePath();
		}
		uploadDir += "/" + request.getRemoteUser() + "/";
		try {
			String filename = importFile.getFileName();
			if (filename.endsWith(Constants.CSV_SUFFIX)) {
				// Create the CSVFormat object
				CSVFormat format = CSVFormat.RFC4180.withHeader()
						.withDelimiter(';');
				CSVParser parser = new CSVParser(new FileReader(
						ImportUtils.saveFile(importFile, uploadDir)), format);
				int i = 0, total = 0;
				for (CSVRecord csvExchange : parser.getRecords()) {
					Exchange exchange = new Exchange();
					exchange.setCode(csvExchange
							.get(Constants.EXCHANGES_IMPORT_HEADER1));
					exchange.setName(csvExchange
							.get(Constants.EXCHANGES_IMPORT_HEADER2));
					exchange.setDescription(csvExchange
							.get(Constants.EXCHANGES_IMPORT_HEADER3));
					exchange.setWebsiteAddress(csvExchange
							.get(Constants.EXCHANGES_IMPORT_HEADER4));
					exchange.setApiAddress(csvExchange
							.get(Constants.EXCHANGES_IMPORT_HEADER5));
					exchange.setFeeAddress(csvExchange
							.get(Constants.EXCHANGES_IMPORT_HEADER6));
					exchange.setRestInterface(new Boolean(csvExchange
							.get(Constants.EXCHANGES_IMPORT_HEADER7)));
					if (exchangeManager.getExchangeByCode(exchange.getCode()) == null) {
						exchangeManager.create(exchange);
						i++;
					}
					total++;
				}
				// close the parser
				parser.close();
//		        getFacesContext().addMessage("messages", 
//		        		new FacesMessage(FacesMessage.SEVERITY_INFO, "Info", "PrimeFaces Rocks."));
//		        getFacesContext().getExternalContext().getFlash().setKeepMessages(true);
//				addMessage("exchanges.import.imported");
//				addMessage("exchanges.import.importedSummary", new Object[] {
//						i, total - i });
				addFacesMessage("exchanges.import.imported");
				addFacesMessage("exchanges.import.importedSummary", new Object[] {
						i, total - i });
			} else {
				addFacesError("exchanges.import.error");
			}
		} catch (IOException e) {
			addFacesError("exchanges.import.error");
		}
		return "list";
	}

	public String delete() {

		exchangeManager.delete(selectedExchange);
		addFacesMessage("exchanges.deleted");
		return "list";
	}

	public String edit() {

		if (code == null) {
			code = new String(getParameter("code"));
		}
		selectedExchange = exchangeManager.getExchangeByCode(code);
		return "edit";
	}

	public String save() {

		boolean isUpdate = (exchangeManager.getExchangeByCode(selectedExchange
				.getCode()) == null) ? false : true;
		if (!isUpdate) {
			exchangeManager.create(selectedExchange);
			addFacesMessage("exchanges.added");
		} else {
			exchangeManager.update(selectedExchange);
			addFacesMessage("exchanges.updated");
		}
		return "list";
	}
}

dev/src/src/main/java/com/gconsulting/webapp/action/MenuController.java
package com.gconsulting.webapp.action;

import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.servlet.http.HttpServletRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Scope;
import org.springframework.security.authentication.AuthenticationTrustResolver;
import org.springframework.security.authentication.AuthenticationTrustResolverImpl;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContext;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;

import com.gconsulting.Constants;
import com.gconsulting.model.Role;
import com.gconsulting.model.User;
import com.gconsulting.service.UserManager;
import com.gconsulting.service.impl.UserManagerImpl;

@Scope("session")
// @Component("menuController")
@Controller("menuController")
public class MenuController extends BasePage implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7204659847632369338L;
	private String id;
	private User user = new User();

	public MenuController() {

		super();
		userManager = new UserManagerImpl();
	}

	private void getUserFromDB() {

		HttpServletRequest request = getRequest();
		// if a user's id is passed in
		if (id != null) {
			log.debug("Editing user, id is: " + id);
			// lookup the user using that id
			user = userManager.getUser(id);
		} else {
			if (request.getRemoteUser() != null) {
				user = userManager.getUserByUsername(request.getRemoteUser());
			} else {
				user = null;
			}
		}
		if (user != null) {
			if (user.getUsername() != null) {
				user.setConfirmPassword(user.getPassword());
				if (isRememberMe()) {
					// if user logged in with remember me, display a warning
					// that they can't change passwords
					log.debug("checking for remember me login...");
					log.trace("User '" + user.getUsername()
							+ "' logged in with cookie");
					addFacesMessage("userProfile.cookieLogin");
				}
			}
		}		
	}
	
	@PostConstruct
	public void init() {
		getUserFromDB();
	}

	@Override
	@Autowired
	public void setUserManager(@Qualifier("userManager") UserManager userManager) {
		this.userManager = userManager;
	}

	public void registerUserNewsletter() {
		/*
		 * TODO: Register insterted E-Mail and display message (Optional): send
		 * confirmation email.
		 */
		addFacesMessage("website.home.newsletterOK");
	}

	public boolean getUserLoggedIn() {

		if (user != null) {
			return true;
		} else {
			return false;
		}
	}

	public void setId(String id) {
		this.id = id;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getTheme() {

//		if (user == null) {
//			init();
//		}
		getUserFromDB();
		return user.getTheme();
	}

	public boolean isAdmin() {

		if (user == null) {
			init();
		}
		for (Role role : user.getRoles()) {
			if (role.getName().equalsIgnoreCase(Constants.ADMIN_ROLE)) {
				return true;
			}
		}
		return false;
	}
//
//	public boolean isUser() {
//
//		for (Role role : user.getRoles()) {
//			if (role.getName().equalsIgnoreCase(Constants.USER_ROLE)) {
//				return true;
//			}
//		}
//		return false;
//	}

	public String create() {

		HttpServletRequest request = getRequest();
		// if a user's id is passed in
		if (id != null) {
			log.debug("Editing user, id is: " + id);
			// lookup the user using that id
			user = userManager.getUser(id);
		} else {
			user = userManager.getUserByUsername(request.getRemoteUser());
		}
		if (user.getUsername() != null) {
			user.setConfirmPassword(user.getPassword());
			if (isRememberMe()) {
				// if user logged in with remember me, display a warning that
				// they can't change passwords
				log.debug("checking for remember me login...");
				log.trace("User '" + user.getUsername()
						+ "' logged in with cookie");
				addFacesMessage("userProfile.cookieLogin");
			}
		}
		return "home";
	}

	/**
	 * Convenience method for view templates to check if the user is logged in
	 * with RememberMe (cookies).
	 * 
	 * @return true/false - false if user interactively logged in.
	 */
	public boolean isRememberMe() {

		if (user != null && user.getId() == null)
			return false; // check for add()
		AuthenticationTrustResolver resolver = new AuthenticationTrustResolverImpl();
		SecurityContext ctx = SecurityContextHolder.getContext();
		if (ctx != null) {
			Authentication auth = ctx.getAuthentication();
			return resolver.isRememberMe(auth);
		}
		return false;
	}
}

dev/src/src/main/webapp/layouts/defaultAboutFAQ.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<meta http-equiv="Cache-Control" content="no-store" />
	<meta http-equiv="Pragma" content="no-cache" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link rel="icon" href="#{request.contextPath}/images/favicon.ico" />
	<title><ui:insert name="title">Home</ui:insert> |
		#{text['webapp.name']}</title>
	<ui:include src="/common/assetsFAQ.xhtml" />
</h:head>
<f:view>
	<body id="#{bodyId}">
		<div id="header" class="navbar navbar-default navbar-fixed-top"
			role="navigation">
			<div class="navbar-header">
				<ul class="nav navbar-nav navbar-left">
					<li><a class="navbar-brand" href="#{request.contextPath}/home">
							Cash BTC</a></li>
				</ul>
			</div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav navbar-right">
					<!-- li><a class="navbar-brand"
						href="#{request.contextPath}/about#contact">#{text['website.headerMenu.uploadReceipt']}</a></li -->
					<li><a href="#{request.contextPath}/sell">#{text['website.headerMenu.sell']}</a></li>
					<li><a href="#{request.contextPath}/about#faq">#{text['website.headerMenu.help']}</a></li>
					<li><a href="#{request.contextPath}/about#fees">#{text['website.headerMenu.liquidity']}</a></li>
					<li><a href="#{request.contextPath}/contact">#{text['website.footerMenu.contact']}</a></li>
				</ul>
			</div>
		</div>
		<div id="content" class="container">
			<div class="row">
				<ui:insert name="body" />
			</div>
		</div>
		<div id="footer" class="container navbar navbar-default">
			<div class="row">
				<div class="col-md-4 text-left">
					<div class="footer-left">
						<p>
							<font size="3"> <a href="#{request.contextPath}/home">
									<span>Cash BTC</span>
							</a>
							</font>
						</p>
						<p>
							"<i>#{text['website.home.tagline']}</i>"
						</p>
					</div>
				</div>
				<div class="col-md-4 text-center">
					<a href="#" target="_blank" title="Coming Soon"> <i
						class="social fa fa-twitter fa-2x"></i>
					</a> <a href="https://www.facebook.com/cashBTC.it" target="_blank">
						<i class="social fa fa-facebook fa-2x"></i>
					</a>
					<h:outputText value="#{text['website.social.bitcointalk2']}"
						escape="false" />
				</div>
				<div class="col-md-4 text-left ">
					<div class="row text-center">
						<a href="#{request.requestURL}?locale=it"> <i
							class="flag-icon flag-icon-it"></i>
						</a>
						<p:spacer width="50" height="10" />
						<a href="#{request.requestURL}?locale=en"> <i
							class="flag-icon flag-icon-gb"></i>
						</a>
					</div>
					<!-- div class="row footer-right-about text-right">
						<h:outputText value="#{text['website.home.nearestOutlet']}"
							escape="false" />
					</div>
					<div class="row footer-right-about text-right">
						<h:outputText value="#{text['website.home.checkBalance']}"
							escape="false" />
					</div>
					<div class="row footer-right-about text-right">
						<h:outputText value="#{text['website.home.currencyConverter']}"
							escape="false" />
					</div>
					<div class="row footer-right-about text-right">
						<h:outputText value="#{text['website.home.terms']}" escape="false" />
					</div>
					<div class="row footer-right-about text-right">
						<h:outputText value="#{text['website.home.disclaimer']}"
							escape="false" />
					</div-->
				</div>
			</div>
			<div class="row">
				<div class="col-md-3"></div>
				<div class="col-md-6 text-center copyright-website">
					<a href="#{request.contextPath}/terms#terms">#{text['website.footerMenu.terms']}</a>
					<p:spacer width="10" height="0" />
					<a href="#{request.contextPath}/terms#privacy">#{text['website.footerMenu.privacy']}</a>
				</div>
				<div class="col-md-3"></div>
			</div>
			<div class="row text-center copyright-website">
				<i class="fa fa-copyright"></i> Copyright #{text['website.url']}
				#{text['copyright.year']}. #{text['website.copyright']}
			</div>
		</div>
		<ui:insert name="scripts" />
	</body>
</f:view>
</html>

dev/src/src/main/webapp/layouts/defaultAdmin.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<meta http-equiv="Cache-Control" content="no-store" />
	<meta http-equiv="Pragma" content="no-cache" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link rel="icon" href="#{request.contextPath}/images/favicon.ico" />
	<title><ui:insert name="title">Home</ui:insert> |
		#{text['webapp.name']}</title>
	<ui:include src="/common/assets.xhtml" />
</h:head>
<f:view>
	<body id="#{bodyId}"
		onload="PrimeFaces.changeTheme('#{menuController.theme}')">
		<div class="navbar-fixed-top">
			<ui:fragment rendered="#{menuController.admin}">
				<ui:include src="/layouts/menu-admin.xhtml" />
			</ui:fragment>
		</div>
		<div class="container" id="content">
			<!-- p:growl id="messages" showDetail="true" / -->
			<p:messages id="messages" showDetail="true" autoUpdate="true"
				closable="true" />
			<div class="row">
				<ui:insert name="body" />
			</div>
		</div>
		<div id="footer" class="container navbar navbar-fixed-bottom">
			<div class="row">
				<div class="col-md-6 text-left">
					<div class="footer-left">#{text['webapp.version']}</div>
				</div>
				<div class="col-md-6">
					<div class="col-md-12 text-right">
						<p:clock pattern="E MMM dd HH:mm:ss yyyy" mode="server"
							autoSync="true" syncInterval="60000" />
					</div>
					<p:spacer width="100%" height="1" />
					<div class="footer-right text-right">
						<a href="#{request.requestURL}?locale=en"> <i
							class="flag-icon flag-icon-gb"></i>
						</a>
						<!-- a href="#{request.requestURL}?locale=es" -->
						<i class="flag-icon flag-icon-es desaturate"></i>
						<!-- /a -->
						<a href="#{request.requestURL}?locale=it"> <i
							class="flag-icon flag-icon-it"></i>
						</a>
						<!-- a href="#{request.requestURL}?locale=ru" -->
						<i class="flag-icon flag-icon-ru desaturate"></i>
						<!-- /a -->
						<!-- a href="#{request.requestURL}?locale=de" -->
						<i class="flag-icon flag-icon-de desaturate"></i>
						<!-- /a -->
						<!-- a href="#{request.requestURL}?locale=fr" -->
						<i class="flag-icon flag-icon-fr desaturate"></i>
						<!-- /a -->
						<!-- a href="#{request.requestURL}?locale=sa" -->
						<i class="flag-icon flag-icon-sa desaturate"></i>
						<!-- /a -->
						<!-- a href="#{request.requestURL}?locale=cn" -->
						<i class="flag-icon flag-icon-cn desaturate"></i>
						<!-- /a -->
						<!-- a href="#{request.requestURL}?locale=jp" -->
						<i class="flag-icon flag-icon-jp desaturate"></i>
						<!-- /a -->
					</div>
				</div>
			</div>
			<div class="row text-center copyright-website">
				<i class="fa fa-copyright"></i> Copyright cashBTC.co
				#{text['copyright.year']}. #{text['website.copyright']}
			</div>
		</div>
		<ui:insert name="scripts" />
	</body>
</f:view>
</html>

dev/src/src/main/webapp/layouts/menu-admin.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<ui:composition>
	<h:form>
		<p:menubar>
			<p:menuitem value="Coin Anaλytics" url="/app/home">
				<a class="navbar-brand" href="#{request.contextPath}/app/home">
					Cash BTC
				</a>
			</p:menuitem>
			<p:submenu label="#{text['menu.admin']}" icon="ui-icon-gear">
				<p:menuitem value="#{text['menu.admin.exchanges']}"
					url="/app/settings/listExchanges" />
			</p:submenu>
			<p:submenu label="Help" icon="ui-icon-help">
				<p:menuitem value="Contents" url="#" />
				<p:submenu label="Search" icon="ui-icon-search">
					<p:submenu label="Text">
						<p:menuitem value="Workspace" url="#" />
					</p:submenu>
					<p:menuitem value="File" url="#" />
				</p:submenu>
			</p:submenu>
			<p:submenu style="position: absolute; right: 18px;"
				label="#{text['menu.user.hello']} #{menuController.user.username}">
				<p:menuitem value="#{text['menu.user.myProfile']}"
					url="/app/myProfile/editProfile" icon="ui-icon-contact" />
				<p:menuitem value="#{text['menu.admin.users']}"
					url="/app/admin/users" />
				<p:menuitem value="#{text['home.activeUsers']}"
					url="/app/admin/activeUsers" />
				<p:separator />
				<p:menuitem value="#{text['user.logout']}"
					url="/app/myProfile/logout" icon="ui-icon-power" />
			</p:submenu>
		</p:menubar>
	</h:form>
</ui:composition>
</html>